### PR TITLE
Added New Module - Tag

### PR DESCRIPTION
**Pull request by techyminati**
Can be used with .tagall - to tag all members, & .admins to tag all admins in chat

### CODE REVIEW

**Comment by ElytrA8** [comment]
@techyminati .all

**Comment by ElytrA8** [comment]
@techyminati @all⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣⁣

**Comment by techyminati** [comment]
okay should i make command as .all

**Comment by ElytrA8** [comment]
Merged Manually With required Changes

**Comment by techyminati** [comment]
Cool

**Comment by ElytrA8** [comment]
Antivirus is dependent on some other dependency code so I didn't merged
But I tried my best

**Comment by techyminati** [comment]
No issue Sar

**Comment by ElytrA8** [comment]
@techyminati Thanks for the PR

**Comment by aktham3210** [comment]
@ElytrA8 L

**Pull request closed without merging**
