### PR TITLE
Update torrent.py

### PR DESCRIPTION
**Pull request by rokibhasansagar**
cyberboysumanjay's torrent search api address moved from heroku to internal

### CODE REVIEW

**Comment by FrosT2k5** [comment]
So it works now?

**Comment by rokibhasansagar** [comment]
> So it works now? With this new url... Need to check

It should work as the website api is identical.
Works in similar script (in Userge, actually), but do test and review.

**Comment by ElytrA8** [comment]
OwO

**Comment by ElytrA8** [comment]
OwO

**Comment by FrosT2k5** [comment]
> OwO

Lol this feature alive after soo long XD

**Pull request merged**
